### ISSUE TITLE
New FS Storage Adapter not saving Images

### ISSUE THREAD

**Issue by radiovisual** [keystonejs/keystone-test-project#12]
I am having a problem testing out the new FS Storage Adapter. You can recreate the problem by taking the following steps:
1. Using keystone-test-project, update `models/Post.js` to use the FS Adapter:
   
   ``` js
   var storage = new keystone.Storage({
       adapter: keystone.Storage.Adapters.FS,
       fs: {
           path: keystone.expandPath('./uploads'),
           publicPath: '/public/uploads/',
       },
       ...
   });
   
   Post.add({
       ...
       image: { type: Types.File, storage: storage },
       ...
   });
   ```
2. Launch the keystone-test-project with `node keystone`
3. Browse to the `Post` section of the CMS, create a new Post and upload a photo.
4. Save that Post (The flash message should report that the save was successful).
5. Now browse back to the Post listing page: http://localhost:3000/keystone/posts
6. Click to open the Post you just saved.
7. Confirm that the Image you uploaded to the Post is not listed, nor is it saved in the `uploads` folder

**Comment by JedWatson** [comment]
I found two issues, one in the `File` field that I've just fixed in Keystone master. This was crashing on upload due to a `this` reference.

The second is a little more significant; It looks like the File field UI is submitting data in the wrong format. I'll fix that but in the meantime, you can use the API Test in this project to test uploading files (feel free to copy the format and add more tests, too)

To use it:
- comment out all the tests in [this file](https://github.com/keystonejs/keystone-test-project/blob/master/tests/api-react/index.js#L9) except the last File one on line 9
- start this app then navigate to [localhost:3000/api](http://localhost:3000/api)

**Comment by radiovisual** [comment]
Seems the upload test in `test/api-react/file/1-File.js` is halted by an API error (which I opened in Issue #13). The test is halted after the call to `/keystone/api/files/create` because the test is looking for a `json` response, but instead it gets an `Uncaught InvalidStateError` in the response.

**Comment by JedWatson** [comment]
Pretty sure this has been resolved. Please re-open if you can still replicate the issue. Thanks!
